pipeline:

  push-mautic-image:
    image: plugins/ecr
    group: build
    registry: 269461048441.dkr.ecr.ap-southeast-2.amazonaws.com
    repo: mautic
    secrets: [ ecr_access_key, ecr_secret_key ]
    tags: 
      - v${DRONE_TAG}
      - latest
    dockerfile: Dockerfile
    region: ap-southeast-2
    when:
      event: [ tag ]
      branch: [ travlr ]

  deploy-mautic:
    image: travlrdev/k8s-jobs-updater-rollout-status
    namespace: production
    deployment: mautic
    repo: 269461048441.dkr.ecr.ap-southeast-2.amazonaws.com/mautic
    tag: v${DRONE_TAG}
    kubernetes_server: ${KUBERNETES_SERVER}
    kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    secrets:
      - kubernetes_server
      - kubernetes_cert
      - kubernetes_token
    when:
      event: tag