pipeline:

  push-mautic-image:
    image: plugins/ecr
    group: build
    registry: 269461048441.dkr.ecr.ap-southeast-2.amazonaws.com
    repo: mautic
    secrets: [ ecr_access_key, ecr_secret_key ]
    tags: 
      - v${DRONE_TAG}
      - latest
    dockerfile: Dockerfile
    region: ap-southeast-2
    when:
      event: [ tag ]
      branch: [ travlr ]

  update-cronjob-mautic-campaigns-build:
    image: travlrdev/k8s-jobs-updater
    namespace: production
    group: update-cronjob
    job: cronjob-mautic-campaigns-build
    container: [ cronjob-mautic-campaigns-build ]
    repo: 269461048441.dkr.ecr.ap-southeast-2.amazonaws.com/mautic
    tag: v${DRONE_TAG}
    kubernetes_server: ${KUBERNETES_SERVER}
    kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    secrets:
      - kubernetes_server
      - kubernetes_cert
      - kubernetes_token
    when:
      event: tag

  update-cronjob-mautic-emails-broadcast:
    image: travlrdev/k8s-jobs-updater
    namespace: production
    group: update-cronjob
    job: cronjob-mautic-emails-broadcast
    container: [ cronjob-mautic-emails-broadcast ]
    repo: 269461048441.dkr.ecr.ap-southeast-2.amazonaws.com/mautic
    tag: v${DRONE_TAG}
    kubernetes_server: ${KUBERNETES_SERVER}
    kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    secrets:
      - kubernetes_server
      - kubernetes_cert
      - kubernetes_token
    when:
      event: tag

  update-cronjob-mautic-emails-send:
    image: travlrdev/k8s-jobs-updater
    namespace: production
    group: update-cronjob
    job: cronjob-mautic-emails-send
    container: [ cronjob-mautic-emails-send ]
    repo: 269461048441.dkr.ecr.ap-southeast-2.amazonaws.com/mautic
    tag: v${DRONE_TAG}
    kubernetes_server: ${KUBERNETES_SERVER}
    kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    secrets:
      - kubernetes_server
      - kubernetes_cert
      - kubernetes_token
    when:
      event: tag

  update-cronjob-mautic-import:
    image: travlrdev/k8s-jobs-updater
    namespace: production
    group: update-cronjob
    job: cronjob-mautic-import
    repo: 269461048441.dkr.ecr.ap-southeast-2.amazonaws.com/mautic
    container: [ cronjob-mautic-import, cronjob-mautic-reports-scheduler ]
    tag: v${DRONE_TAG}
    kubernetes_server: ${KUBERNETES_SERVER}
    kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    secrets:
      - kubernetes_server
      - kubernetes_cert
      - kubernetes_token
    when:
      event: tag

  update-cronjob-mautic-misc:
    image: travlrdev/k8s-jobs-updater
    namespace: production
    group: update-cronjob
    job: cronjob-mautic-misc
    container: [ cronjob-mautic-email-fetch, cronjob-mautic-social-monitoring, cronjob-mautic-webhooks-process ]
    repo: 269461048441.dkr.ecr.ap-southeast-2.amazonaws.com/mautic
    tag: v${DRONE_TAG}
    kubernetes_server: ${KUBERNETES_SERVER}
    kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    secrets:
      - kubernetes_server
      - kubernetes_cert
      - kubernetes_token
    when:
      event: tag

  deploy-mautic:
    image: travlrdev/k8s-jobs-updater-rollout-status
    namespace: production
    deployment: mautic
    repo: 269461048441.dkr.ecr.ap-southeast-2.amazonaws.com/mautic
    tag: v${DRONE_TAG}
    kubernetes_server: ${KUBERNETES_SERVER}
    kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    secrets:
      - kubernetes_server
      - kubernetes_cert
      - kubernetes_token
    when:
      event: tag